# FROM ubuntu:latest
FROM python:3.8.1
COPY ./app_compair.py /quiz/api/
COPY ./svm_gamma=0.0005_C=7.joblib /quiz/
COPY ./requirements.txt /exp/requirements.txt
RUN pip3 install --no-cache-dir -r /exp/requirements.txt
WORKDIR /quiz
#CMD ["python3", "./plot_graphs.py"]